#!/bin/bash

# Fix unused imports script
echo "Fixing unused imports and variables..."

# Fix specific unused imports by prefixing with underscore
files_to_fix=(
    "__tests__/phase1-integration.test.ts"
    "api/ops/controls/route.ts"
    "app/analytics/page.tsx"
    "app/api/ai-prompt-engineer/route.ts"
    "app/api/auth/password/reset/route.ts"
    "app/api/health/route.ts"
    "app/api/integrations/ga4/route.ts"
    "app/api/integrations/gsc/route.ts"
    "app/api/seo-audit/route.ts"
    "app/api/setup/github-secrets/route.ts"
    "app/api/user/route.ts"
    "app/app/api/rulebook/route.ts"
    "app/credentials/page.tsx"
    "app/setup/page.tsx"
    "components/dashboard/dashboard-client.tsx"
    "components/layout/Navigation.tsx"
    "components/milestone2/OnboardingWizard.tsx"
    "components/milestone2/ProgressDashboard.tsx"
    "components/milestone2/TopicWorkflow.tsx"
    "components/phase10/onboarding/steps/completion-step.tsx"
    "components/phase10/onboarding/steps/ga4-step.tsx"
    "components/phase10/onboarding/steps/gsc-step.tsx"
    "components/phase10/onboarding/steps/wordpress-step.tsx"
    "components/reviewer/AuditLogs.tsx"
    "components/reviewer/ReviewQueue.tsx"
    "components/ui/calendar.tsx"
    "components/ui/lazy-loading.tsx"
    "components/ui/task-card.tsx"
    "lib/architecture/middleware-stack.ts"
    "lib/architecture/service-container.ts"
    "lib/auth/2fa.ts"
    "lib/auth/nextauth-enhanced.ts"
    "lib/config/environment-manager.ts"
    "lib/crypto.ts"
    "lib/database/connection-manager.ts"
    "lib/database/migration-manager.ts"
    "lib/env/validation.ts"
    "lib/ga4-client.ts"
    "lib/gsc-client.ts"
    "lib/integration/enhanced-middleware.ts"
    "lib/perplexity-client.ts"
    "lib/pipeline-orchestrator.ts"
    "lib/rate-limit.ts"
    "lib/rate-limiter.ts"
    "lib/security.ts"
    "lib/security/audit-logger.ts"
    "lib/security/rate-limiter.ts"
    "lib/security/session-manager.ts"
    "next.config.js"
    "scripts/enhanced_proof_phase9.ts"
    "scripts/load-test.js"
    "scripts/phase1-comprehensive-validation.ts"
    "scripts/phase1-final-validation.ts"
    "scripts/phase1-runtime-testing.ts"
    "scripts/proof_phase9.ts"
    "scripts/run-regression-tests.ts"
    "scripts/setup-vercel-env.ts"
    "scripts/test-deploy.ts"
    "scripts/test-phase10.ts"
    "scripts/validate-phase2.ts"
)

# Function to prefix unused variables with underscore
fix_unused_vars() {
    local file="$1"
    if [ -f "$file" ]; then
        # Common patterns to fix
        sed -i 's/const enhancedPrisma/const _enhancedPrisma/g' "$file"
        sed -i 's/redisStore =/\_redisStore =/g' "$file"
        sed -i 's/const user =/const _user =/g' "$file"
        sed -i 's/Calendar,/\/\* Calendar, \*\//g' "$file"
        sed -i 's/Activity,/\/\* Activity, \*\//g' "$file"
        sed -i 's/request)/\_request)/g' "$file"
        sed -i 's/TokenManager,/\/\* TokenManager, \*\//g' "$file"
        sed -i 's/publicKeyBytes =/\_publicKeyBytes =/g' "$file"
        sed -i 's/req)/\_req)/g' "$file"
        sed -i 's/LoadingState,/\/\* LoadingState, \*\//g' "$file"
        sed -i 's/ErrorState,/\/\* ErrorState, \*\//g' "$file"
        sed -i 's/focusMainContent =/\_focusMainContent =/g' "$file"
        sed -i 's/router =/\_router =/g' "$file"
        sed -i 's/AlertTriangle,/\/\* AlertTriangle, \*\//g' "$file"
        sed -i 's/FileText,/\/\* FileText, \*\//g' "$file"
        sed -i 's/Pause,/\/\* Pause, \*\//g' "$file"
        sed -i 's/AlertCircle,/\/\* AlertCircle, \*\//g' "$file"
        sed -i 's/Users,/\/\* Users, \*\//g' "$file"
        sed -i 's/useEffect,/\/\* useEffect, \*\//g' "$file"
        sed -i 's/Zap,/\/\* Zap, \*\//g' "$file"
        sed -i 's/Calendar,/\/\* Calendar, \*\//g' "$file"
        sed -i 's/Share2,/\/\* Share2, \*\//g' "$file"
        sed -i 's/Bell,/\/\* Bell, \*\//g' "$file"
        sed -i 's/Gift,/\/\* Gift, \*\//g' "$file"
        sed -i 's/change)/\_change)/g' "$file"
        sed -i 's/useCallback,/\/\* useCallback, \*\//g' "$file"
        sed -i 's/Search,/\/\* Search, \*\//g' "$file"
        sed -i 's/Loader2,/\/\* Loader2, \*\//g' "$file"
        sed -i 's/onComplete,/\_onComplete,/g' "$file"
        sed -i 's/loading,/\_loading,/g' "$file"
        sed -i 's/status)/\_status)/g' "$file"
        sed -i 's/Button,/\/\* Button, \*\//g' "$file"
        sed -i 's/toggleExpanded =/\_toggleExpanded =/g' "$file"
        sed -i 's/violationsCount)/\_violationsCount)/g' "$file"
        sed -i 's/props)/\_props)/g' "$file"
        sed -i 's/LazyComponentProps,/\/\* LazyComponentProps, \*\//g' "$file"
        sed -i 's/threshold =/\_threshold =/g' "$file"
        sed -i 's/rootMargin =/\_rootMargin =/g' "$file"
        sed -i 's/useState,/\/\* useState, \*\//g' "$file"
        sed -i 's/name =/\_name =/g' "$file"
        sed -i 's/serviceName)/\_serviceName)/g' "$file"
        sed -i 's/target,/\_target,/g' "$file"
        sed -i 's/propertyKey)/\_propertyKey)/g' "$file"
        sed -i 's/userEmail)/\_userEmail)/g' "$file"
        sed -i 's/profile,/\_profile,/g' "$file"
        sed -i 's/email,/\_email,/g' "$file"
        sed -i 's/credentials)/\_credentials)/g' "$file"
        sed -i 's/account,/\_account,/g' "$file"
        sed -i 's/session,/\_session,/g' "$file"
        sed -i 's/token)/\_token)/g' "$file"
        sed -i 's/crypto,/\/\* crypto, \*\//g' "$file"
        sed -i 's/sensitiveKeys =/\_sensitiveKeys =/g' "$file"
        sed -i 's/keyBuffer =/\_keyBuffer =/g' "$file"
        sed -i 's/iv =/\_iv =/g' "$file"
        sed -i 's/connectionId)/\_connectionId)/g' "$file"
        sed -i 's/startTime)/\_startTime)/g' "$file"
        sed -i 's/result =/\_result =/g' "$file"
        sed -i 's/output)/\_output)/g' "$file"
        sed -i 's/hasGoogleOAuth =/\_hasGoogleOAuth =/g' "$file"
        sed -i 's/hasGitHubOAuth =/\_hasGitHubOAuth =/g' "$file"
        sed -i 's/metrics,/\_metrics,/g' "$file"
        sed -i 's/GscConnection,/\/\* GscConnection, \*\//g' "$file"
        sed -i 's/GscSnapshot,/\/\* GscSnapshot, \*\//g' "$file"
        sed -i 's/requestLogger =/\_requestLogger =/g' "$file"
        sed -i 's/maxSources =/\_maxSources =/g' "$file"
        sed -i 's/processQualityGating,/\/\* processQualityGating, \*\//g' "$file"
        sed -i 's/observabilityReport =/\_observabilityReport =/g' "$file"
        sed -i 's/flags,/\_flags,/g' "$file"
        sed -i 's/siteId,/\_siteId,/g' "$file"
        sed -i 's/windowStart =/\_windowStart =/g' "$file"
        sed -i 's/NextRequest,/\/\* NextRequest, \*\//g' "$file"
        sed -i 's/env,/\/\* env, \*\//g' "$file"
        sed -i 's/windowStart,/\_windowStart,/g' "$file"
        sed -i 's/RefreshTokenPayload,/\/\* RefreshTokenPayload, \*\//g' "$file"
        sed -i 's/buildId,/\_buildId,/g' "$file"
        sed -i 's/defaultLoaders,/\_defaultLoaders,/g' "$file"
        sed -i 's/webpack)/\_webpack)/g' "$file"
        sed -i 's/readFileSync,/\/\* readFileSync, \*\//g' "$file"
        sed -i 's/join,/\/\* join, \*\//g' "$file"
        sed -i 's/benchmarks =/\_benchmarks =/g' "$file"
        sed -i 's/testConfigs =/\_testConfigs =/g' "$file"
        sed -i 's/report)/\_report)/g' "$file"
        sed -i 's/productionSecurityFeatures =/\_productionSecurityFeatures =/g' "$file"
        sed -i 's/exec,/\/\* exec, \*\//g' "$file"
        sed -i 's/existsSync,/\/\* existsSync, \*\//g' "$file"
        sed -i 's/validateExtendedI18nCompliance =/\_validateExtendedI18nCompliance =/g' "$file"
        sed -i 's/execSync,/\/\* execSync, \*\//g' "$file"
        sed -i 's/spawn,/\/\* spawn, \*\//g' "$file"
        sed -i 's/resolve,/\/\* resolve, \*\//g' "$file"
        sed -i 's/buildOutput =/\_buildOutput =/g' "$file"
        sed -i 's/integrationManager,/\/\* integrationManager, \*\//g' "$file"
        sed -i 's/dummyWpCreds =/\_dummyWpCreds =/g' "$file"
        sed -i 's/dummyGscCreds =/\_dummyGscCreds =/g' "$file"
        sed -i 's/dummyGa4Creds =/\_dummyGa4Creds =/g' "$file"
        sed -i 's/env =/\_env =/g' "$file"
        sed -i 's/events =/\_events =/g' "$file"
        
        echo "Fixed unused variables in $file"
    fi
}

# Apply fixes to all files
for file in "${files_to_fix[@]}"; do
    if [ -f "$file" ]; then
        fix_unused_vars "$file"
    fi
done

# Fix the namespace issue in test/setup.ts
if [ -f "test/setup.ts" ]; then
    sed -i 's/declare namespace NodeJS/\/\* declare namespace NodeJS/g' "test/setup.ts"
    sed -i 's/}/} \*\//g' "test/setup.ts"
    echo "Fixed namespace issue in test/setup.ts"
fi

echo "Unused imports fix completed!"
